from CRUD.models.mysql_models.transactionhistoric import transactionhistoric
from django.utils import timezone

class historicTransaction(transactionhistoric.Model):
    venta_sk = transactionhistoric.CharField(max_length=255)
    venta_sk_n = transactionhistoric.CharField(max_length=255)
    priceListId = transactionhistoric.CharField(max_length=255)
    sucursal = transactionhistoric.CharField(max_length=10)
    caja = transactionhistoric.CharField(max_length=10)
    almacen = transactionhistoric.CharField(max_length=10)
    hora24h = transactionhistoric.CharField(max_length=10)
    ffecha = transactionhistoric.CharField(max_length=10)
    horastr = transactionhistoric.CharField(max_length=10)
    codeSucursal = transactionhistoric.CharField(max_length=10)
    fecha_process = transactionhistoric.CharField(max_length=10)
    sellerID = transactionhistoric.CharField(max_length=255)
    SKU = transactionhistoric.CharField(max_length=255)
    quantity = transactionhistoric.CharField(max_length=255)
    priceWoVAT = transactionhistoric.CharField(max_length=255)
    IVA = transactionhistoric.CharField(max_length=255)
    total_disc = transactionhistoric.CharField(max_length=255)
    precio_brutoSD = transactionhistoric.CharField(max_length=255)
    subtotal = transactionhistoric.CharField(max_length=255)
    partyIdentifier = transactionhistoric.CharField(max_length=255)
    partyCode = transactionhistoric.CharField(max_length=255)
    total = transactionhistoric.CharField(max_length=255)
    fp_amount = transactionhistoric.CharField(max_length=255)
    cambio = transactionhistoric.CharField(max_length=255)
    fp_code = transactionhistoric.CharField(max_length=255)
    fp_codeName = transactionhistoric.CharField(max_length=255)
    fopa = transactionhistoric.CharField(max_length=255)
    FolioSig = transactionhistoric.CharField(max_length=255)
    pncd = transactionhistoric.CharField(max_length=255)
    description = transactionhistoric.CharField(max_length=255)
    barcode = transactionhistoric.CharField(max_length=255)
    guardado = transactionhistoric.CharField(max_length=255)
    NumLine = transactionhistoric.CharField(max_length=255)
    created_at = transactionhistoric.DateTimeField(default=timezone.now)