# Generated by Django 4.2.6 on 2023-10-20 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HANA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolioSiguientePorSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('folio', models.CharField(max_length=255)),
            ],
        ),
    ]
