# Generated by Django 4.2.6 on 2023-10-19 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='historicTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta_sk', models.CharField(max_length=255)),
                ('venta_sk_n', models.CharField(max_length=255)),
                ('priceListId', models.CharField(max_length=255)),
                ('sucursal', models.CharField(max_length=10)),
                ('caja', models.CharField(max_length=10)),
                ('almacen', models.CharField(max_length=10)),
                ('hora24h', models.CharField(max_length=10)),
                ('ffecha', models.CharField(max_length=10)),
                ('horastr', models.CharField(max_length=10)),
                ('codeSucursal', models.CharField(max_length=10)),
                ('fecha_process', models.CharField(max_length=10)),
                ('sellerID', models.CharField(max_length=255)),
                ('SKU', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('priceWoVAT', models.CharField(max_length=255)),
                ('IVA', models.CharField(max_length=255)),
                ('total_disc', models.CharField(max_length=255)),
                ('precio_brutoSD', models.CharField(max_length=255)),
                ('subtotal', models.CharField(max_length=255)),
                ('partyIdentifier', models.CharField(max_length=255)),
                ('partyCode', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('fp_amount', models.CharField(max_length=255)),
                ('cambio', models.CharField(max_length=255)),
                ('fp_code', models.CharField(max_length=255)),
                ('fp_codeName', models.CharField(max_length=255)),
                ('fopa', models.CharField(max_length=255)),
                ('FolioSig', models.CharField(max_length=255)),
                ('pncd', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255)),
                ('guardado', models.CharField(max_length=255)),
                ('NumLine', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SYS_PCOBROTRANS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skComplet', models.CharField(max_length=255)),
                ('venta_sk0', models.CharField(max_length=255)),
                ('guardado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SYS_PDETALLEDEVOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skComplet', models.CharField(max_length=255)),
                ('venta_sk0', models.CharField(max_length=255)),
                ('guardado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SYS_PDETALLETRANS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skComplet', models.CharField(max_length=255)),
                ('venta_sk0', models.CharField(max_length=255)),
                ('guardado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SYS_PDEVOLUCIONES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skComplet', models.CharField(max_length=255)),
                ('venta_sk0', models.CharField(max_length=255)),
                ('guardado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SYS_PPAGOTANS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skComplet', models.CharField(max_length=255)),
                ('venta_sk0', models.CharField(max_length=255)),
                ('guardado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SYS_PTRANSACCIONES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skComplet', models.CharField(max_length=255)),
                ('venta_sk0', models.CharField(max_length=255)),
                ('guardado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TransacctionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta_sk', models.CharField(max_length=255)),
                ('venta_sk_n', models.CharField(max_length=255)),
                ('priceListId', models.CharField(max_length=255)),
                ('sucursal', models.CharField(max_length=10)),
                ('caja', models.CharField(max_length=10)),
                ('almacen', models.CharField(max_length=10)),
                ('hora24h', models.CharField(max_length=10)),
                ('ffecha', models.CharField(max_length=10)),
                ('horastr', models.CharField(max_length=10)),
                ('codeSucursal', models.CharField(max_length=10)),
                ('fecha_process', models.CharField(max_length=10)),
                ('sellerID', models.CharField(max_length=255)),
                ('SKU', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('priceWoVAT', models.CharField(max_length=255)),
                ('IVA', models.CharField(max_length=255)),
                ('total_disc', models.CharField(max_length=255)),
                ('precio_brutoSD', models.CharField(max_length=255)),
                ('subtotal', models.CharField(max_length=255)),
                ('partyIdentifier', models.CharField(max_length=255)),
                ('partyCode', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('fp_amount', models.CharField(max_length=255)),
                ('cambio', models.CharField(max_length=255)),
                ('fp_code', models.CharField(max_length=255)),
                ('fp_codeName', models.CharField(max_length=255)),
                ('fopa', models.CharField(max_length=255)),
                ('FolioSig', models.CharField(max_length=255)),
                ('pncd', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('barcode', models.CharField(max_length=255)),
                ('NumLine', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
