from CRUD.models.mongo_models.transactionMongo import transactionMongo
from django.utils import timezone

class TransacctionPago(transactionMongo.Model):
    venta_sk = transactionMongo.CharField(max_length=255)
    venta_sk_n = transactionMongo.CharField(max_length=255)
    priceListId = transactionMongo.CharField(max_length=255)
    sucursal = transactionMongo.CharField(max_length=10)
    caja = transactionMongo.CharField(max_length=10)
    almacen = transactionMongo.CharField(max_length=10)
    hora24h = transactionMongo.CharField(max_length=10)
    ffecha = transactionMongo.CharField(max_length=10)
    horastr = transactionMongo.CharField(max_length=10)
    codeSucursal = transactionMongo.CharField(max_length=10)
    fecha_process = transactionMongo.CharField(max_length=10)
    sellerID = transactionMongo.CharField(max_length=255)
    SKU = transactionMongo.CharField(max_length=255)
    quantity = transactionMongo.CharField(max_length=255)
    priceWoVAT = transactionMongo.CharField(max_length=255)
    IVA = transactionMongo.CharField(max_length=255)
    total_disc = transactionMongo.CharField(max_length=255)
    precio_brutoSD = transactionMongo.CharField(max_length=255)
    subtotal = transactionMongo.CharField(max_length=255)
    partyIdentifier = transactionMongo.CharField(max_length=255)
    partyCode = transactionMongo.CharField(max_length=255)
    total = transactionMongo.CharField(max_length=255)
    fp_amount = transactionMongo.CharField(max_length=255)
    cambio = transactionMongo.CharField(max_length=255)
    fp_code = transactionMongo.CharField(max_length=255)
    fp_codeName = transactionMongo.CharField(max_length=255)
    fopa = transactionMongo.CharField(max_length=255)
    FolioSig = transactionMongo.CharField(max_length=255)
    pncd = transactionMongo.CharField(max_length=255)
    # impn = transactionMongo.CharField(max_length=255)
    description = transactionMongo.CharField(max_length=255)
    barcode = transactionMongo.CharField(max_length=255)
    NumLine = transactionMongo.CharField(max_length=255)
    created_at = transactionMongo.DateTimeField(default=timezone.now)