# Generated by Django 4.1.11 on 2023-09-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fichasdeposito',
            fields=[
                ('IdFichaDeposito', models.AutoField(primary_key=True, serialize=False)),
                ('FkIdTienda', models.IntegerField()),
                ('Deposito', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Fecha', models.DateField()),
                ('Tipo', models.CharField(max_length=125)),
                ('ArchivoMobo', models.CharField(max_length=250)),
                ('Rechazado', models.BooleanField()),
                ('Motivo', models.CharField(max_length=45)),
                ('Comentario', models.CharField(max_length=250)),
                ('Mail', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'fichasdeposito',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta_sk', models.CharField(max_length=255)),
                ('venta_sk_n', models.IntegerField()),
                ('origin', models.CharField(max_length=55)),
                ('ffecha', models.CharField(max_length=55)),
                ('fecha_process', models.CharField(max_length=55)),
                ('hora', models.CharField(max_length=55)),
                ('sucursal', models.CharField(max_length=10)),
                ('almacen', models.CharField(max_length=10)),
                ('caja', models.CharField(max_length=10)),
                ('tipo_venta', models.CharField(max_length=10)),
                ('sellerID', models.CharField(max_length=10)),
                ('SKU', models.CharField(max_length=55)),
                ('quantity', models.IntegerField()),
                ('priceWoVAT', models.BooleanField(default=False)),
                ('IVA', models.BooleanField(default=False)),
                ('total_disc', models.BooleanField(default=False)),
                ('gross_up', models.BooleanField(default=False)),
                ('balance', models.BooleanField(default=False)),
                ('importe_c_desc', models.BooleanField(default=False)),
                ('subtotal', models.BooleanField(default=False)),
                ('total', models.BooleanField(default=False)),
                ('fp_id', models.CharField(max_length=55)),
                ('fp_amount', models.BooleanField(default=False)),
                ('fp_installments', models.CharField(max_length=55)),
                ('fp_bank', models.CharField(max_length=55)),
                ('fp_date', models.CharField(max_length=55)),
                ('items', models.JSONField()),
                ('formas_pago', models.JSONField()),
            ],
        ),
    ]
