# Generated by Django 4.1.11 on 2023-09-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_fichasdeposito_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='formas_pago',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='items',
        ),
    ]
