# Generated by Django 4.1.11 on 2023-09-26 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0004_alter_transaction_iva_alter_transaction_balance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='tipo_venta',
            new_name='codeSucursal',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='fp_bank',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='fp_date',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='fp_id',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='fp_installments',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='gross_up',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='importe_c_desc',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='origin',
        ),
        migrations.AddField(
            model_name='transaction',
            name='change',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='fp_code',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='fp_codeName',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='hora24h',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='horastr',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='precio_brutoSD',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='priceListId',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='IVA',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='SKU',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fecha_process',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='ffecha',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='fp_amount',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='priceWoVAT',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='quantity',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sellerID',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='subtotal',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='total_disc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='venta_sk_n',
            field=models.CharField(max_length=255),
        ),
    ]
