# Generated by Django 4.1.11 on 2023-09-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0005_rename_tipo_venta_transaction_codesucursal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransacctionPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venta_sk', models.CharField(max_length=255)),
                ('venta_sk_n', models.CharField(max_length=255)),
                ('priceListId', models.CharField(max_length=255)),
                ('sucursal', models.CharField(max_length=10)),
                ('caja', models.CharField(max_length=10)),
                ('almacen', models.CharField(max_length=10)),
                ('hora24h', models.CharField(max_length=10)),
                ('ffecha', models.CharField(max_length=10)),
                ('horastr', models.CharField(max_length=10)),
                ('codeSucursal', models.CharField(max_length=10)),
                ('fecha_process', models.CharField(max_length=10)),
                ('sellerID', models.CharField(max_length=255)),
                ('SKU', models.CharField(max_length=255)),
                ('quantity', models.CharField(max_length=255)),
                ('priceWoVAT', models.CharField(max_length=255)),
                ('IVA', models.CharField(max_length=255)),
                ('total_disc', models.CharField(max_length=255)),
                ('precio_brutoSD', models.CharField(max_length=255)),
                ('subtotal', models.CharField(max_length=255)),
                ('total', models.CharField(max_length=255)),
                ('fp_amount', models.CharField(max_length=255)),
                ('change', models.CharField(max_length=255)),
                ('fp_code', models.CharField(max_length=255)),
                ('fp_codeName', models.CharField(max_length=255)),
            ],
        ),
    ]
