# Generated by Django 4.1.11 on 2023-09-26 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0006_transacctionpago'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
