# Generated by Django 4.1.11 on 2023-09-28 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0007_delete_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='transaccionHana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=255)),
                ('skuHana', models.CharField(max_length=255)),
                ('descr', models.CharField(max_length=255)),
                ('catego', models.CharField(max_length=255)),
            ],
        ),
    ]
