# Generated by Django 4.1.11 on 2023-10-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0008_transaccionhana'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacctionpago',
            name='partyCode',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacctionpago',
            name='partyIdentifier',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
