# Generated by Django 4.1.11 on 2023-10-03 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0009_transacctionpago_partycode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='extraxtTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumAtCard', models.CharField(max_length=255)),
                ('DocNum', models.CharField(max_length=255)),
            ],
        ),
    ]
