# Generated by Django 4.1.11 on 2023-10-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0010_extraxtticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacctionpago',
            name='fopa',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
