# Generated by Django 4.1.11 on 2023-10-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0011_transacctionpago_fopa'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacctionpago',
            name='FolioSig',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
