# Generated by Django 4.1.11 on 2023-10-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0012_transacctionpago_foliosig'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacctionpago',
            name='barcode',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacctionpago',
            name='description',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacctionpago',
            name='pncd',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
