# Generated by Django 4.1.11 on 2023-10-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0013_transacctionpago_barcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SYS_PTRANSACCIONES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skComplet', models.CharField(max_length=255)),
                ('venta_sk0', models.CharField(max_length=255)),
                ('guardado', models.CharField(max_length=255)),
            ],
        ),
    ]
