# Generated by Django 4.1.11 on 2023-10-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0014_sys_ptransacciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='SYS_PCOBROTRANS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skComplet', models.CharField(max_length=255)),
                ('venta_sk0', models.CharField(max_length=255)),
                ('guardado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SYS_PDETALLEDEVOL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skComplet', models.CharField(max_length=255)),
                ('venta_sk0', models.CharField(max_length=255)),
                ('guardado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SYS_PDETALLETRANS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skComplet', models.CharField(max_length=255)),
                ('venta_sk0', models.CharField(max_length=255)),
                ('guardado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SYS_PDEVOLUCIONES',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skComplet', models.CharField(max_length=255)),
                ('venta_sk0', models.CharField(max_length=255)),
                ('guardado', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SYS_PPAGOTANS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skComplet', models.CharField(max_length=255)),
                ('venta_sk0', models.CharField(max_length=255)),
                ('guardado', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='transacctionpago',
            name='barcode',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacctionpago',
            name='description',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacctionpago',
            name='pncd',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
