# Generated by Django 4.1.11 on 2023-10-16 22:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0015_sys_pcobrotrans_sys_pdetalledevol_sys_pdetalletrans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacctionpago',
            name='barcode',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacctionpago',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transacctionpago',
            name='description',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacctionpago',
            name='pncd',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
