# Generated by Django 4.1.11 on 2023-10-16 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0016_transacctionpago_barcode_transacctionpago_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolioSiguientePorSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sucursal', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=255)),
                ('folio', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='transacctionpago',
            name='barcode',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacctionpago',
            name='description',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
