# Generated by Django 4.1.11 on 2023-10-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0018_historictransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historictransaction',
            old_name='change',
            new_name='cambio',
        ),
        migrations.RenameField(
            model_name='transacctionpago',
            old_name='change',
            new_name='cambio',
        ),
        migrations.AddField(
            model_name='historictransaction',
            name='guardado',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
