# Generated by Django 4.1.11 on 2023-10-17 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0019_rename_change_historictransaction_cambio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historictransaction',
            name='NumLine',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transacctionpago',
            name='NumLine',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
