from django.db import models
from django.utils import timezone


class TransacctionPago(models.Model):
    venta_sk = models.CharField(max_length=255)
    venta_sk_n = models.CharField(max_length=255)
    priceListId = models.CharField(max_length=255)
    sucursal = models.CharField(max_length=10)
    caja = models.CharField(max_length=10)
    almacen = models.CharField(max_length=10)
    hora24h = models.CharField(max_length=10)
    ffecha = models.CharField(max_length=10)
    horastr = models.CharField(max_length=10)
    codeSucursal = models.CharField(max_length=10)
    fecha_process = models.CharField(max_length=10)
    sellerID = models.CharField(max_length=255)
    SKU = models.CharField(max_length=255)
    quantity = models.CharField(max_length=255)
    priceWoVAT = models.CharField(max_length=255)
    IVA = models.CharField(max_length=255)
    total_disc = models.CharField(max_length=255)
    precio_brutoSD = models.CharField(max_length=255)
    subtotal = models.CharField(max_length=255)
    partyIdentifier = models.CharField(max_length=255)
    partyCode = models.CharField(max_length=255)
    total = models.CharField(max_length=255)
    fp_amount = models.CharField(max_length=255)
    cambio = models.CharField(max_length=255)
    fp_code = models.CharField(max_length=255)
    fp_codeName = models.CharField(max_length=255)
    fopa = models.CharField(max_length=255)
    FolioSig = models.CharField(max_length=255)
    pncd = models.CharField(max_length=255)
    # impn = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    barcode = models.CharField(max_length=255)
    NumLine = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now)

class SYS_PDEVOLUCIONES(models.Model):
    skComplet = models.CharField(max_length=255)
    venta_sk0 = models.CharField(max_length=255)
    guardado = models.CharField(max_length=255)
    
class SYS_PDETALLETRANS(models.Model):
    skComplet = models.CharField(max_length=255)
    venta_sk0 = models.CharField(max_length=255)
    guardado = models.CharField(max_length=255)
    
class SYS_PPAGOTANS(models.Model):
    skComplet = models.CharField(max_length=255)
    venta_sk0 = models.CharField(max_length=255)
    guardado = models.CharField(max_length=255)
    
class SYS_PTRANSACCIONES(models.Model):
    skComplet = models.CharField(max_length=255)
    venta_sk0 = models.CharField(max_length=255)
    guardado = models.CharField(max_length=255)
    
class SYS_PCOBROTRANS(models.Model):
    skComplet = models.CharField(max_length=255)
    venta_sk0 = models.CharField(max_length=255)
    guardado = models.CharField(max_length=255)
    
class SYS_PDETALLEDEVOL(models.Model):
    skComplet = models.CharField(max_length=255)
    venta_sk0 = models.CharField(max_length=255)
    guardado = models.CharField(max_length=255)


class historicTransaction(models.Model):
    venta_sk = models.CharField(max_length=255)
    venta_sk_n = models.CharField(max_length=255)
    priceListId = models.CharField(max_length=255)
    sucursal = models.CharField(max_length=10)
    caja = models.CharField(max_length=10)
    almacen = models.CharField(max_length=10)
    hora24h = models.CharField(max_length=10)
    ffecha = models.CharField(max_length=10)
    horastr = models.CharField(max_length=10)
    codeSucursal = models.CharField(max_length=10)
    fecha_process = models.CharField(max_length=10)
    sellerID = models.CharField(max_length=255)
    SKU = models.CharField(max_length=255)
    quantity = models.CharField(max_length=255)
    priceWoVAT = models.CharField(max_length=255)
    IVA = models.CharField(max_length=255)
    total_disc = models.CharField(max_length=255)
    precio_brutoSD = models.CharField(max_length=255)
    subtotal = models.CharField(max_length=255)
    partyIdentifier = models.CharField(max_length=255)
    partyCode = models.CharField(max_length=255)
    total = models.CharField(max_length=255)
    fp_amount = models.CharField(max_length=255)
    cambio = models.CharField(max_length=255)
    fp_code = models.CharField(max_length=255)
    fp_codeName = models.CharField(max_length=255)
    fopa = models.CharField(max_length=255)
    FolioSig = models.CharField(max_length=255)
    pncd = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    barcode = models.CharField(max_length=255)
    guardado = models.CharField(max_length=255)
    NumLine = models.CharField(max_length=255)
    created_at = models.DateTimeField(default=timezone.now)